spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update


log4j:
  logger:
    org:
      hibernate:
        type: trace